### PR TITLE
Fixing test errors and compatibility with newer dependency gems

### PR DESCRIPTION
**Pull request by morozgrafix**
I was getting tons of errors running tests after bundle update, this should make tests pass. Also added simple UTF-8  test to address #4 

I'm running with following setup:

```
$ bundle show
Gems included by the bundle:
  * ansi (1.5.0)
  * builder (3.2.2)
  * bundler (1.12.5)
  * exiftool (0.7.0)
  * json (2.0.2)
  * minitest (5.9.0)
  * minitest-great_expectations (0.0.5)
  * minitest-reporters (1.1.11)
  * rake (11.2.2)
  * ruby-progressbar (1.8.1)
  * yard (0.9.5)

$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

$ exiftool -ver
10.25
```

### CODE REVIEW

**Comment by morozgrafix** [comment]
Looks like I'm running into old version of exiftools on Travis CI again.
Travis CI has `Exiftool.exiftool_version = 8.60` I'm running `10.25` locally. Somewhere between those versions exiftool has added support for `preview_tiff` metadata. Matthew do you think you will have some time to bump up the version on Travis setup? Thanks.

**Comment by morozgrafix** [comment]
I've temporarily added `preview_tiff` to list of ignored keys to make Travis-CI happier, until you get a chance to update to more recent version of exiftools there.
I wasn't able to reproduce #4 and added a bare minimum test for utf-8 fields.

**Comment by mceachen** [comment]
Thanks for the PR!

**Comment by morozgrafix** [comment]
Thanks for taking care of this, looking forward to a new version of the gem. Apologies, I just realized that I've submitted somewhat messy PR and you had to sift through it.

**Comment by mceachen** [comment]
The PR wasn't messy at all, and I released v0.8.0 with this PR. Thanks again for your help!

**Pull request closed without merging**
